### ISSUE TITLE
download as csv doesn't work

### ISSUE THREAD

**Issue by StCyr** [DMPbelgium/roadmap#85]
```
Sep 26 10:26:32 dmponline 9bc6d88a2440[1233]: F, [2023-09-26T08:26:32.829343 #15] FATAL -- : [125b44e7-1857-4572-8945-a04912376f0f]   
Sep 26 10:26:32 dmponline 9bc6d88a2440[1233]: [125b44e7-1857-4572-8945-a04912376f0f] ArgumentError (wrong number of arguments (given 7, expected 1..6)):
Sep 26 10:26:32 dmponline 9bc6d88a2440[1233]: [125b44e7-1857-4572-8945-a04912376f0f]   
Sep 26 10:26:32 dmponline 9bc6d88a2440[1233]: [125b44e7-1857-4572-8945-a04912376f0f] config/initializers/ugent.rb:301:in `as_csv'
Sep 26 10:26:32 dmponline 9bc6d88a2440[1233]: [125b44e7-1857-4572-8945-a04912376f0f] config/initializers/ugent.rb:109:in `show_csv'
```

I think `@show_research_outputs` should be removed from:

```
  def show_csv
    send_data @plan.as_csv(current_user, @show_sections_questions,
                           @show_unanswered,
                           @selected_phases,
                           @show_custom_sections,
                           @show_coversheet,
                           @show_research_outputs),
              filename: "#{file_name}.csv"
```

@nicolasfranck could you confirm?

**Comment by nicolasfranck** [comment]
@StCyr see my latest commit: https://github.com/DMPbelgium/roadmap/commit/3700b534f734cbc49c7ae897302df8e8b5f48644

Should work now.

**Comment by StCyr** [comment]
Yes, it works now.

thanks
